site_name: Python Game Development
site_description: A guide to learning Pygame through interactive lessons and projects.
site_author: South Bend Code School

theme: 
  name: material
  
  palette:
    scheme: default
  logo: assets/logo.png
  favicon: assets/logo.png
  font: 
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/00-Installation/Installation.md
    - Starter Game Template: getting-started/01-Starter-Game-Template/starter_game_template.md
  - Mini Lessons:
    - Pygame:
      - Drawing Shapes: pygame/drawing-shapes/draw_shapes.md
      - Keyboard Input: pygame/keyboard-input/keyboard_input.md
      - Colors: pygame/colors/colors.md
      - Handling Mouse Input: pygame/mouse-input/mouse_input.md
      - Sound Effects: pygame/sound-effects/coming_soon.md
      - Background Music: pygame/background-music/coming_soon.md
      - Displaying Images: pygame/images/coming_soon.md
      - Animating Sprites: pygame/animated-sprites/animated_sprites.md
      - Player Class: pygame/player-class/coming_soon.md
      - Collision Detection: pygame/collision-detection/coming_soon.md
      - Frame Independent Movement: pygame/framerate-independence/framerate_independence.md
      - Parallax Scrolling: pygame/parallax-scrolling/coming_soon.md
      - Full Screen: pygame/full-screen/coming_soon.md
      - Physics: pygame/physics/coming_soon.md
      - Particles: pygame/particles/coming_soon.md
      - Publish on itch.io: pygame/publish-itch/coming_soon.md
    - Python:
      - Coming Soon: python/p01-Indendation/indendation.md
  - Student Challenges:
    - One Button Game: challeges/one-button-game/one_button.md
  - Full Game Examples:
    - Breakout: full-game-examples/breakout-game/coming_soon.md
    - Flappy Bird: full-game-examples/flappy-bird-game/coming_soon.md
    - Pong: full-game-examples/pong-game/coming_soon.md
    - Snake: full-game-examples/snake-game/coming_soon.md
    - Barnacle Briggs: full-game-examples/curse-of-barnacle-briggs/barnacle-briggs.md

plugins:
  - search

markdown_extensions:
  - attr_list  # Required for Material button styling to work
  - toc:
      permalink: true
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
extra:
  include:
    - "**/*.py"