site_name: Python Game Development
site_description: A guide to learning Pygame through interactive lessons and projects.
site_author: South Bend Code School

theme: 
  name: material
  
  palette:
    scheme: default
  logo: assets/logo.png
  favicon: assets/logo.png
  font: 
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/00-Installation/Installation.md
    - Starter Game Template: getting-started/01-Starter-Game-Template/starter_game_template.md
  - Mini Lessons:
    - Pygame:
      - Drawing Shapes: pygame/01-Drawing-Shapes/draw_shapes.md
      - Handling Keyboard Input: pygame/02-Handling-Keyboard-Input/keyboard_input.md
      - Colors: pygame/03-Colors/colors.md
      - Handling Mouse Input: pygame/04-Handling-Mouse-Input/mouse_input.md
      - Sound Effects: pygame/05-Sound-Effects/todo.md
      - Background Music: pygame/06-Background-Music/todo.md
      - Displaying Images: pygame/07-Displaying-Images/todo.md
      - Animating Sprites: pygame/08-Animating-Sprites/todo.md
      - Basic Collision Detection: pygame/09-Basic-Collision-Detection/todo.md
      - Player Class: pygame/11-Player-Class/todo.md
      - Enemy Class: pygame/10-Enemy-Class/todo.md
      - Frame Rate Independence: pygame/12-Frame Rate Independence/framerate_indpendence.md
      - Scrolling Background: pygame/13-Scrolling-Background/assets/todo.md
    - Python:
      - Coming Soon: python/p01-Indendation/indendation.md
  - Student Challenges:
    - One Button Game: challeges/one-button-game/one_button.md
  - Full Game Examples:
    - Breakout: full-game-examples/breakout/coming_soon.md
    - Flappy Bird: full-game-examples/flappy-bird/coming_soon.md
    - Pong: full-game-examples/pong/coming_soon.md
    - Snake: full-game-examples/snake/coming_soon.md
    - Barnacle Briggs: full-game-examples/the-curse-of-barnacle-briggs/barnacle-briggs.md

plugins:
  - search

markdown_extensions:
  - attr_list  # Required for Material button styling to work
  - toc:
      permalink: true
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
extra:
  include:
    - "**/*.py"